fix building tests when char is unsigned
when char is unsigned it's uint8_t which doesn't match the type declared
for the key of the map, so it fails with

error: non-constant-expression cannot be narrowed from type
'typename std::enable_if<std::is_integral<char>::value && sizeof(char) == sizeof(char), char>::type'
(aka 'char') to 'const signed char' in initializer list

etc